# Generated by Django 4.1.2 on 2022-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='ProjectImage'),
        ),
    ]
